### PR TITLE
Change .ts to .js in package.json

### PR DESCRIPTION
**Pull request by rubenhensen**
I changed the package.json main and types entries to .ts but they need to be .js.

### CODE REVIEW

**Comment by joshnuss** [comment]
Thanks for the catch!

**Comment by suda** [comment]
@rubenhensen The type definition file is indeed `index.d.ts` (there's no `index.d.js` built). The `.js` suffix confuses Rollup and it tries to parse the type definition file as a regular JS causing `Error: Unexpected token`:

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/svelte-local-storage-store/dist/index.d.ts (3:8)
1: import { Writable } from 'svelte/store';
2: 
3: declare function writable<T>(key: string, initialValue: T): Writable<T>;
           ^
4: 
5: export { writable };
```

Can we change it back?

**Comment by joshnuss** [comment]
Hi @suda,

I just published a fix in `0.2.4`
Can you try it and confirm it's working
https://www.npmjs.com/package/svelte-local-storage-store/v/0.2.4

**Comment by suda** [comment]
@joshnuss it works! Thanks for super fast turnaround! :heart:

**Comment by joshnuss** [comment]
Welcome!

**Pull request merged**
