### PR TITLE
Upgrade to Svelte v4

### PR DESCRIPTION
**Pull request by celldra**
I've upgraded all the packages in the `package.json` and ran the tests that are in the repository, it has passed all of them.

```
 ✓ test/localStorageStore.test.ts (15)
   ✓ writable() (1)
     ✓ it works, but raises deprecation warning
   ✓ persisted() (14)
     ✓ uses initial value if nothing in local storage
     ✓ uses existing value if data already in local storage
     ✓ set() (2)
       ✓ replaces old value
       ✓ adds new value
     ✓ update() (2)
       ✓ replaces old value
       ✓ adds new value
     ✓ subscribe() (1)
       ✓ publishes updates
     ✓ handles duplicate stores with the same key
     ✓ handles window.storage event (4)
       ✓ sets storage when key matches
       ✓ sets store to null when value is null
       ✓ doesn't update store when key doesn't match
       ✓ doesn't update store when there are no subscribers
     ✓ allows custom serialize/deserialize functions
     ✓ lets you switch storage type

 Test Files  1 passed (1)
      Tests  15 passed (15)
   Start at  12:23:22
   Duration  704ms (transform 66ms, setup 0ms, collect 54ms, tests 15ms, environment 357ms, prepare 87ms)
   ```
   
   Let me know if any extra changes are required, I'm happy to help out.

### CODE REVIEW

**Comment by joshnuss** [comment]
Hi @celldra,

I think this package should still support `3.x` as well. 
Can you set the package version to `^3.48.0 || ^4.12.0`?

Also, if you don't mind, can you prefix the commit message with `feat:`, that will trigger a new npm version when merged.

**Comment by joshnuss** [comment]
Or maybe event simpler would be to use a version spec like `> 3.48.0`

**Comment by celldra** [comment]
Yeah, that sounds much better. I'm not to familiar with NPM so I apologise about that. I can make the changes now

**Comment by joshnuss** [comment]
Resolved in #195

**Pull request closed without merging**
